name: GitHub CI Deploy

on:
  push:
    tags:
      # Matches all the tags in the format major.minor.patch (e.g. 1.12.3).
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
  MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_SIGNING_KEY_ID }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew assembleRelease ktlintCheck lintRelease testReleaseUnitTest -s
      - name: Upload coverage reports
        # Uploads all the coverage reports to Codecov.io:
        # -Z -> if the upload of a report fails, the build fails too
        # -s -> searches in the paths in which CoveragePlugin generates the coverage reports
        # -f -> uploads the XML files found in the search paths (specified with -s)
        # -X -> excludes the tools not needed by this project
        run: bash <(curl -s https://codecov.io/bash) -Z -s "**/build/coverageReport/test*Coverage/test*Coverage.xml" -f "*.xml" -X gcov -X coveragepy -X xcode -X gcovout
  test1:
    name: test 1/3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew
      - name: Run tests on API 16, 17, 18, 19
        env:
          ROBOLECTRIC_MIN_API: 16
          ROBOLECTRIC_MAX_API: 19
        run: ./ci/run-tests.sh
  test2:
    name: test 2/3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew
      - name: Run tests on API 21, 22, 23, 24
        env:
          ROBOLECTRIC_MIN_API: 21
          ROBOLECTRIC_MAX_API: 24
        run: ./ci/run-tests.sh
  test3:
    name: test 3/3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew
      - name: Run tests on API 25, 26, 27, 28
        env:
          ROBOLECTRIC_MIN_API: 25
          ROBOLECTRIC_MAX_API: 28
        run: ./ci/run-tests.sh
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test1, test2, test3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew
      - name: Extract tag
        id: tag-extractor
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/*/}
      - name: Deploy
        env:
          DEPLOY_TAG: ${{ steps.tag-extractor.outputs.TAG }}
        run: ./gradlew publishLibrary --no-parallel -s -PVERSION_NAME=$DEPLOY_TAG -PmavenCentralRepositoryUsername=$MAVEN_CENTRAL_USERNAME -PmavenCentralRepositoryPassword=$MAVEN_CENTRAL_PASSWORD
